
service: s3-mailer


provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-2
  memorySize: 128
  environment:
    # You need to set up a .env.yaml file of your own with your app password in it
    APP_PASS: ${file(./.env.yml):APP_PASS}

iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:*"
    Resource: "*"
 

# you can add packaging information here
package:
  include:
    - mailer/**


functions:
  s3_notification:
    handler: handler.s3_notification
    events:
      - s3:
          bucket: athaman-s3-notification
          event: s3:ObjectCreated:*
          # rules:
          #   - suffix: .pdf

